export const FETCH_USERINFO = 'PROFILE/FETCH_USERINFO';
export const FETCH_USERINFO_SUCCESS = 'PROFILE/FETCH_USERINFO_SUCCESS';
export const FETCH_USERINFO_FAILURE = 'PROFILE/FETCH_USERINFO_FAILURE';

export const FETCH_NEW_MESSAGE = 'PROFILE/FETCH_NEW_MESSAGE';
export const FETCH_NEW_MESSAGE_SUCCESS = 'PROFILE/FETCH_NEW_MESSAGE_SUCCESS';
export const FETCH_NEW_MESSAGE_FAILURE = 'PROFILE/FETCH_NEW_MESSAGE_FAILURE';
