export const FETCH_RECOMMANDWEIBO = "FETCH_RECOMMANDWEIBO";
export const FETCH_RECOMMANDWEIBO_SUCCESS = "FETCH_RECOMMANDWEIBO_SUCCESS";
export const FETCH_RECOMMANDWEIBO_FAILURE = "FETCH_RECOMMANDWEIBO_FAILURE";
